events {}
http {
    server {
        listen 80;
        location / {
            return 200 '{"status":"ok","server":"upstream-mock"}';
            add_header Content-Type application/json;
        }
        location /health {
            return 200 'ok';
        }
    }
}
